server:
  port: 8080

spring:
  application:
    name: item-relationship-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health, threaddump, loggers, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, diskSpace
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 4004

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: WARN
    org.springframework: INFO
    net.catenax.irs: INFO

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger-ui
  writer-with-order-by-keys: true

irs:
  apiUrl: http://irs.int.demo.catena-x.net
  partsTreeMaxDepth: 100

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      digitalTwinRegistry:
        url: http://localhost:4242

blobstore:
  endpoint: "${MINIO_URL}"
  accessKey: "${MINIO_ACCESS_KEY}"
  secretKey: "${MINIO_SECRET_KEY}"
  bucketName: irsbucket